### ISSUE TITLE
ScaleSet example code does not work

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/tf2pulumi#105]
The example [here]( https://pulumi.io/reference/pkg/nodejs/pulumi/azure/compute/#example-usage-with-managed-disks-recommended) on this [line](https://github.com/pulumi/pulumi-azure/blob/3fa6e00723842ba39a5b310a5ebd487f57ba2f34/sdk/nodejs/compute/scaleSet.ts#L88):
```
loadBalancerInboundNatRulesIds: [pulumi.all(lbnatpool.map(v => v.id)).apply(id => id.map(v => v)[1])],
```
does not work. You cannot `map` a `NatPool`.

**Comment by lukehoban** [comment]
Moved to `tf2pulumi` as this looks like an issue in that tool used to generate this example.

**Comment by Frassle** [comment]
This looks like a maxItemsOne issue which is likely fixed in the new converter.
