### ISSUE TITLE
Codegen for loops in doc examples isn't great.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/tf2pulumi#108]
For example, we have https://github.com/pulumi/pulumi-aws/blob/6597a59b9b5c887a5484c3c3198182fbd205f368/sdk/nodejs/ec2/getSubnetIds.ts#L24-L25

```ts
 * for (let i = 0; i < exampleSubnetIds.apply(exampleSubnetIds => exampleSubnetIds.ids.length); i++) {
 *     exampleSubnet.push(aws.ec2.getSubnet);
```

Note: this code doesn't compile (both because of comparison to a `.apply`), and also because of the lack of args to `push`.

ideally this would just be:

```ts
for (const id of exampleSubnetIds) {
  exampleSubnet.push(aws.ec2.getSubnet({ id }));
}
```

If the `for ... of` is a bit too hard to detect, we should still at least produce something more like:

```ts
for (let i = 0; i < exampleSubnetIds.ids.length; i++) {
     exampleSubnet.push(aws.ec2.getSubnet({ id: exampleSubnetIds.ids[i] });
}
```

**Comment by pgavlin** [comment]
Fairly sure this is fixed with the new code generator.
