### ISSUE TITLE
Installation of tf2pulumi issues

### ISSUE THREAD

**Issue by chrisvdg** [pulumi/tf2pulumi#115]
I tried to install the `tf2pulumi` as part of a trial to convert the OpenvCloud terraform provider to a pulumi one. It took me quite some time to get the tool compiled running into a few bumbs.
I've tried installing this tool on ubuntu16.04 (docker container) and 18.04.

This issue describes all mayor issues I've encountered while trying to install so feel free to separate them out when they are confirmed and deserve their own issue.

- 1: The readme feel a bit outdated, it describes that `dep` is used as depency manager while the project has `go.mod` and `go.sum` files, indicating that `go mod` is used

- 2: The go get command described in the readme fails
```
go get -d github.com/pulumi/tf2pulumi/...
go: finding github.com/pulumi/tf2pulumi/... latest
go: finding github.com/pulumi/tf2pulumi v0.5.1
go: downloading github.com/pulumi/tf2pulumi v0.5.1
go: extracting github.com/pulumi/tf2pulumi v0.5.1
go get github.com/pulumi/tf2pulumi/...: no matching versions for query "latest"
```

I continued using `go get -d github.com/pulumi/tf2pulumi`

- 3: Even that fails as a dependency (a terraform dependency I think) has been moved:
`git.apache.org/thrift.git` -> `github.com/apache/thrift`

So I continued cloning this repo and added a replace in go.mod: `git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999`

- 4: Installation of dependencies fails due to missing binary dependency

```
...
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
...
```

resolved by installing bzr with:
```
apt install bzr -y
```

- 5: Running `go install` again:
```
go install
go: github.com/ugorji/go/codec@v0.0.0-20181012064053-8333dd449516 used for two different module paths (github.com/ugorji/go and github.com/ugorji/go/codec)
```

I got this fixed by replacing the existing replace line for `github.com/ugorji/go ...` with:
```
github.com/ugorji/go v1.1.4 => github.com/ugorji/go/codec v0.0.0-20190204201341-e444a5086c43
```

And yes, I totally missed the line that says the binaries are available in the github releases until I got it compiled...

**Comment by pgavlin** [comment]
Thanks for the report!

Which version of Go were you using?

**Comment by chrisvdg** [comment]
go version go1.12.9 linux/amd64

**Comment by mikhailshilkov** [comment]
Got the same error today:

> go: github.com/ugorji/go/codec@v0.0.0-20181012064053-8333dd449516 used for two different module paths (github.com/ugorji/go and github.com/ugorji/go/codec)

fixed by the same workaround above.

`go version go1.13.1 windows/amd64`

**Comment by Frassle** [comment]
tf2pulumi is deprecated and so no longer needs to be installed.
