### ISSUE TITLE
Broken AWS ACM example

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#117]
### Problem description

The example at https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/acm/#example-usage-1 is broken. It compiles and runs, but the certificate validation process by AWS fails because the arguments for the `aws.route53.Record` resource are wrong. The `name` argument of the `aws.route53.Record` _must_ be set to the `certCertificate.domainValidationOptions[0].resourceRecordName` output of the `aws.acm.Certificate`.

This example is auto-generated from the upstream Terraform example at https://github.com/terraform-providers/terraform-provider-aws/blob/e434b8508563d64e839da349ec563b0b3d61942a/website/docs/r/acm_certificate_validation.html.markdown#dns-validation-with-route-53. The Terraform works, because it specifies the exact `name` of the record, where in the Pulumi example the `name` has been removed.

### Suggestions for a fix

Does the Pulumi doc generator remove `name` arguments for Pulumi's resources because of Pulumi's auto-naming functionality? If so, can we turn this off for this example?

The example should look something like this:
```typescript
import * as aws from "@pulumi/aws";

const certCertificate = new aws.acm.Certificate("cert", {
    domainName: "example.com",
    validationMethod: "DNS",
});
const zone = aws.route53.getZone({
    name: "example.com.",
    privateZone: false,
});
const certValidation = new aws.route53.Record("certValidation", {
    name: certCertificate.domainValidationOptions[0].resourceRecordName, // <-- This line is needed
    records: [certCertificate.domainValidationOptions[0].resourceRecordValue],
    ttl: 60,
    type: certCertificate.domainValidationOptions[0].resourceRecordType,
    zoneId: zone.id,
});
const certCertificateValidation = new aws.acm.CertificateValidation("cert", {
    certificateArn: certCertificate.arn,
    validationRecordFqdns: [certValidation.fqdn],
});
```

**Comment by lukehoban** [comment]
This appears to be fixed at https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificatevalidation/#dns-validation-with-route-53.

```ts
import * as aws from "@pulumi/aws";

const exampleCertificate = new aws.acm.Certificate("exampleCertificate", {
    domainName: "example.com",
    validationMethod: "DNS",
});
const exampleZone = aws.route53.getZone({
    name: "example.com",
    privateZone: false,
});

const certValidation = new aws.route53.Record("certValidation", {
    name: exampleCertificate.domainValidationOptions[0].resourceRecordName,
    records: [exampleCertificate.domainValidationOptions[0].resourceRecordValue],
    ttl: 60,
    type: exampleCertificate.domainValidationOptions[0].resourceRecordType,
    zoneId: exampleZone.then(x => x.zoneId),
});

const certCertificateValidation = new aws.acm.CertificateValidation("cert", {
    certificateArn: exampleCertificate.arn,
    validationRecordFqdns: [certValidation.fqdn],
});

export const certificateArn = certCertificateValidation.certificateArn;
```
