### ISSUE TITLE
Convert count conditional hacks to if statements

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#123]
Terraform users often use `count = "${var_enabled ? 1 : 0}"` as conditional hacks to turn determine when to create resources or not. This gets converted to a for loop such as `for (let i = 0; i < (varEnabled ? 1 : 0); i++) { ... }` when in practice it should be real if statement instead. 

Can `tf2pulumi` determine when a `count = "..."` resolves to `0` or `1` and turn that into a real conditional instead of a for loop?

**Comment by pgavlin** [comment]
> Can `tf2pulumi` determine when a `count = "..."` resolves to `0` or `1` and turn that into a real conditional instead of a for loop?

It would be easy to match exactly the `"${expr ? 1 : 0}"` pattern, but trickier to get the arbitrary cases (symbolic execution, anyone?).
