### ISSUE TITLE
Terraform variable map usage needs `<any>` type hint

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#125]
This variable definition:
```
variable "proxy_map" {
  type        = "map"

  default {
    us-east-1   = "0.0.0.0"
    us-west-2   = "0.0.0.0"
  }
}
```

Becomes
```
export const proxyMap = config.get("proxyMap") || {
    "us-east-1": "0.0.0.0",
    "us-west-2": "0.0.0.0",
}
```

Which TypeScript complains about when accessed in this manner in `tf2pulumi` converted code - e.g. ``${config.proxyMap[`${config.awsRegion}`]}/32``.

Adding the `<any>` type cast makes TypeScript happy:
```
export const proxyMap = config.get("proxyMap") || <any>{
    "us-east-1": "0.0.0.0",
    "us-west-2": "0.0.0.0",
}
```

**Comment by Frassle** [comment]
I'm pretty sure the [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) handles cares like this correctly.
