### ISSUE TITLE
Conserve property order for example derived from terraform

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/tf2pulumi#149]
Goal : Conserve property order for example derived from terraform

See for example [azure.network.ApplicationGateway](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/network/#example-usage)

Pulumi example sorts properties alphabetically (and nested properties) :
```ts
const network = new azure.network.ApplicationGateway("network", {
    backendAddressPools: ...
    backendHttpSettings:  ...
    frontendIpConfigurations: ...
    frontendPorts: ...
    gatewayIpConfigurations: ...
    httpListeners: ...
    location: exampleResourceGroup.location,
    requestRoutingRules: ...
    resourceGroupName: exampleResourceGroup.name,
    sku: {
        capacity: 2,
        name: "Standard_Small",
        tier: "Standard",
    },
});
```

Whereas Terraform example sorts properties by a logical order : 
```ts
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }
  gateway_ip_configuration { ... }
  frontend_port { ... }
  frontend_ip_configuration { ... }
  backend_address_pool { ... }
  backend_http_settings { ... }
  http_listener { ... }
  request_routing_rule { .. }
}
```

The logical order is far better to understand the main properties.

**Comment by Frassle** [comment]
The new converter tries to maintain property order when generating intermediate code. It's up to each language to maintain that in their code generators (which is not always possible). We'll add tests for this when doing matrix testing.
