### ISSUE TITLE
tf2pulumi' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lucasproclc** [pulumi/tf2pulumi#158]
I am trying out the terraform to pulumi and I am stuck with this.  
$ tf2pulumi >my-stack/index.ts  ## I am having problems here - do I go to the "my stack site" to create this index.ts?
I cannot seem to run this.  

Usage
In order to use tf2pulumi to convert a Terraform project to Pulumi TypeScript and then deploy it, you'll first need to install the Pulumi CLI. Once the Pulumi CLI has been installed, navigate to the same directory as the Terraform project you'd like to import and create a new Pulumi TypeScript stack in a subdirectory:
$ pulumi new typescript --dir my-stack (This one I must placed a directory where my terraform sample is located)  - it worked.  
Then run tf2pulumi and redirect its output to a file named index.ts in the directory that contains the Pulumi project you just created:
$ tf2pulumi >my-stack/index.ts  ## I am having problems here - do I go to the "my stack site" to create this index.ts?
If tf2pulumi complains about missing Terraform resource plugins, install those plugins as per the instructions in the error message and re-run the command above.

**Comment by lucasproclc** [comment]
c:\>tf2pulumi
'tf2pulumi' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lucasproclc** [comment]
Sorry accidentally closed it.

**Comment by lukehoban** [comment]
Sounds like you perhaps don’t have `$GOPATH/bin` on your `PATH`?

You can just run `$GOPATH/bin/tf2pulumi` if you’d prefer.

**Comment by lucasproclc** [comment]
I was running it in CMD - and it failed.  I switched to PS1 - it worked.

**Comment by lucasproclc** [comment]
PS C:\go-work\tf2pulumi\$GOPATH\bin> tf2pulumi
tf2pulumi : The term 'tf2pulumi' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tf2pulumi
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (tf2pulumi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\go-work\tf2pulumi\$GOPATH\bin>

**Comment by lucasproclc** [comment]
Just didn't work

**Comment by lukehoban** [comment]
Do you have a `tf2pulumi.exe` in that folder?   

You may need to do `go build -o $GOPATH/bin/tf2pulumi.exe main.go` On Windows?

**Comment by lucasproclc** [comment]
C:\Go\bin>go build -o $GOPATH/bin/tf2pulumi.exe main.go
go: finding github.com/pulumi/tf2pulumi/version latest
go: finding github.com/pulumi/tf2pulumi/convert latest
go: finding github.com/pulumi/tf2pulumi/gen latest
go: finding github.com/pulumi/tf2pulumi/gen/nodejs latest
build command-line-arguments: cannot load github.com/pulumi/tf2pulumi/convert: no matching versions for query "latest"

**Comment by lucasproclc** [comment]
Luke - please advise how to fix this build command-line-arguments: cannot load github.com/pulumi/tf2pulumi/convert: no matching versions for query "latest"

**Comment by lucasproclc** [comment]
Any advise  how to fix this?

**Comment by Frassle** [comment]
tf2pulumi is deprecated, use `pulumi convert --from terraform` instead.
