### ISSUE TITLE
I am trying to run the conversion and I am getting an error.

### ISSUE THREAD

**Issue by mfc19** [pulumi/tf2pulumi#159]
error: creating tree module: Error parsing <myfile.tf>: At 6:14: Unknown token: 6:14 IDENT google-beta

This is shows up all places I am using variables.

**Comment by pgavlin** [comment]
Does your config use HCL2 syntax?

**Comment by mfc19** [comment]
No HCL

**Comment by tmccombs** [comment]
I'm running into this error. I am using HCL2, but it sounds like 0.8.0 should support that. 

The problem line is:

```
  ami                     = module.baseami.ami_id

```

it seems maybe it doesn't support bare identifiers?

**Comment by lukehoban** [comment]
This is almost certainly fixed as part of the new `pulumi convert --from terraform` (https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/).  There isn't a clear repro here to validate that for sure though, so I'll just close out for now.  If there are still issues with the same source code on the new converter, we can re-open a tracking issue at https://github.com/pulumi/pulumi-terraform-bridge.
