### ISSUE TITLE
HCL2: support the builtin providers.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/tf2pulumi#172]
The HCL2 binder lacks support for the builtin providers (e.g. `archive` and `http`). This causes failures when converting examples that use those providers (e.g. the `Lambda` test in `tests/terraform/aws/lambda`).

**Comment by Frassle** [comment]
The [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) is tolerant to missing providers.
