### ISSUE TITLE
unknown method GetSchema for service pulumirpc.ResourceProvider

### ISSUE THREAD

**Issue by pdemagny** [pulumi/tf2pulumi#177]
Hi, i've been trying to convert a Terraform 0.12.24 configuration with **tf2pulumi v0.8.0** and **pulumi v2.2.1**.

After having initialized with:

```bash
pulumi new typescript -f
```

Whatever `tf2pulumi`command i run in my Terraform configuration's directory, it instantly exits with:

```bash
error: rpc error: code = Unimplemented desc = unknown method GetSchema for service pulumirpc.ResourceProvider
```

I have no idea where to go from here :/

**Comment by pdemagny** [comment]
Ok, so i had to add the providers manually with:

```bash
npm install @pulumi/gcp
npm install @pulumi/mongodbatlas
```

And add them to my index.ts file as:

```bash
import * as gcp from '@pulumi/gcp';
import * as atlas from '@pulumi/mongodbatlas';
```

Now i get tons of errors due to usage of functions such as merge/try/format in my Terraform code.
How can i work around this without having to change all my TF code to remove these functions ?

Sorry for the useless issue, but maybe it'll help someone else that didn't understand the error at first, like i did :)

**Comment by isaacraja** [comment]
I'm also getting the same error when trying to convert an existing terraform project to pulumi.

**Comment by manfred0191** [comment]
I am also getting this error after trying to do

tf2pulumi --target-language typescript

error: rpc error: code = Unimplemented desc = unknown service pulumirpc.ResourceProvider

**Comment by manfred0191** [comment]
There are 2 possible reasons for this:

Either the template function doesn't work correctly or you have only 1 shot in a directory to run tf2pulumi. After making changes the 2nd try doesn't work anymore.

You should investigate this further. If I can be of any assistance, feel free to involve me.

**Comment by lukehoban** [comment]
Also reported in https://twitter.com/vincentvdk/status/1535495482138558465.

**Comment by yagnamanirudh** [comment]
Any other possible ways to debug or resolve the below issue 
`tf2pulumi --target-language go`
`error: rpc error: code = Unimplemented desc = GetSchema is not yet implemented`

**Comment by Mistic92** [comment]
I'm getting the same error but for Golang. 
```
╰─ tf2pulumi --target-language go                                                                                                                                                                                                                                                                    
error: rpc error: code = Unimplemented desc = GetSchema is not yet implemented
```
