### ISSUE TITLE
Allow (and most likely default to) emitting Pulumi code in a different folder

### ISSUE THREAD

**Issue by lukehoban** [pulumi/tf2pulumi#187]
In `0.8.0` we changed to defaulting to (and in fact only even really supporting) emitting Pulumi files in to the same folder as the `.tf` files.  This is rarely what users want in practice.  We should at least support an option to emit into another folder - and should likely make that the default (i.e. make it a required parameter).

**Comment by Frassle** [comment]
`pulumi convert` supports "--out" and we'll probably change that to be required in https://github.com/pulumi/pulumi/issues/12842
