### ISSUE TITLE
Build breaks

### ISSUE THREAD

**Issue by johndohoneyjr** [pulumi/tf2pulumi#19]
Tried go get as well, steps to recreate
git clone https://github.com/pulumi/tf2pulumi.git
cd tf2pulumi
make (as shown below)

$ make
=============================
Terraform -> Pulumi converter
=============================
BUILD:
go install -ldflags "-X github.com/tf2pulumi.Version=v0.1.0-dev-1540315421-g44c7c4d" github.com/pulumi/tf2pulumi
# github.com/pulumi/tf2pulumi/il
../../go/src/github.com/pulumi/tf2pulumi/il/builtin_providers.go:31:29: impossible type assertion:
	*schema.Provider does not implement "github.com/terraform-providers/terraform-provider-archive/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider (wrong type for Apply method)
		have Apply(*"github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/hashicorp/terraform/terraform".InstanceState, error)
		want Apply(*"github.com/terraform-providers/terraform-provider-archive/vendor/github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/terraform-providers/terraform-provider-archive/vendor/github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/terraform-providers/terraform-provider-archive/vendor/github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/terraform-providers/terraform-provider-archive/vendor/github.com/hashicorp/terraform/terraform".InstanceState, error)
../../go/src/github.com/pulumi/tf2pulumi/il/builtin_providers.go:41:26: impossible type assertion:
	*schema.Provider does not implement "github.com/terraform-providers/terraform-provider-http/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider (wrong type for Apply method)
		have Apply(*"github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/hashicorp/terraform/terraform".InstanceState, error)
		want Apply(*"github.com/terraform-providers/terraform-provider-http/vendor/github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/terraform-providers/terraform-provider-http/vendor/github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/terraform-providers/terraform-provider-http/vendor/github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/terraform-providers/terraform-provider-http/vendor/github.com/hashicorp/terraform/terraform".InstanceState, error)
make: *** [build] Error 2

**Comment by lukehoban** [comment]
I believe you need to run `make ensure` to get all vendored dependencies prior to running `make`.  We should make sure this is documented in README and/or CONTRIBUTING docs.

**Comment by pgavlin** [comment]
@lukehoban is correct. Due to the complicated interactions between the TF dependency graph and the `pulumi-terraform` dependency graph, we use `dep` to manage dependency versions. You can find complete instructions for building here: https://github.com/pulumi/tf2pulumi#installation
