### ISSUE TITLE
error: rpc error: code = Unimplemented desc = GetSchema is unimplemented

### ISSUE THREAD

**Issue by scarby** [pulumi/tf2pulumi#197]
after running 
```
pulumi new typescript -f 
```
then running 
```tf2pulumi```
i am immediately greeted with the following message:
```
error: rpc error: code = Unimplemented desc = GetSchema is unimplemented 
```

in terms of versions i have
```
tf2pulumi version
v0.8.0
pulumi version
v2.5.0
terraform version
Terraform v0.12.28
```

can anyone suggest what might be happening here?

**Comment by lukehoban** [comment]
Possibly related to https://github.com/pulumi/tf2pulumi/issues/177.  cc @pgavlin who was looking into this recently.

**Comment by scarby** [comment]
i already saw that, not only is the error slightly different but adding providers (kubernetes and gcp) in my case did nothing.

**Comment by lukehoban** [comment]
> but adding providers (kubernetes and gcp)

Do you happen to know the full set of Terraform providers your codebase uses?

**Comment by scarby** [comment]
Only Google and kubernetes

**Comment by avkanumuri** [comment]
I am trying to convert terraform to pulumi and noticing similar issues. 
pulumi version                                                                                                                                   
v2.11.2
tf2pulumi version                                                                                                                         
v0.8.0
Terraform v0.12.29

**Comment by clarkdave** [comment]
I'm also getting the same error trying to convert a fairly simple Terraform/AWS project to Pulumi.

```
$ pulumi version
v2.11.2
$ tf2pulumi version
v0.8.0
$ terraform version
Terraform v0.11.14
+ provider.aws v2.58.0
```

**Comment by yagnamanirudh** [comment]
Any other possible ways to debug or resolve the below issue
`tf2pulumi --target-language go`
`error: rpc error: code = Unimplemented desc = GetSchema is not yet implemented`

**Comment by Frassle** [comment]
New converter tolerates schema fetch failures.
