### ISSUE TITLE
error: no resource plugin 'random' found in the workspace or on your $PATH

### ISSUE THREAD

**Issue by omerlh** [pulumi/tf2pulumi#203]
Trying to convert the following code:
```
resource "random_id" "random_role_id_suffix" {
  byte_length = 2
}
```
Results with error:
error: no resource plugin 'random' found in the workspace or on your $PATH

Terraform plan/apply exist - the plugin is installed as expected

**Comment by leezen** [comment]
Have you run `pulumi plugin install resource random 2.2.0`?

**Comment by lukehoban** [comment]
I just tried this (on a machine with the random plugin installed), and did not see any error.  

I'm going to close as I believe the suggestion @leezen provided should have worked here. If you are still seeing issues here though - please do reopen.
