### ISSUE TITLE
Examples of failing TF import (language-specific)

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/tf2pulumi#204]
C# and Golang fails: https://raw.githubusercontent.com/nickcharlton/terraform-gke/master/gke.tf

Golang fails: https://raw.githubusercontent.com/nickcharlton/terraform-aws-vpc/master/vpc.tf

A few ideas:
1) can we give hits to fix common issues vs. just error text?
2) can we present an "open an issue in Github" button on fail?

**Comment by Frassle** [comment]
These are likely fixed in the [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/).
