### ISSUE TITLE
Comments don't always seem to be extracted correctly

### ISSUE THREAD

**Issue by leezen** [pulumi/tf2pulumi#210]
Example: https://www.pulumi.com/docs/reference/pkg/aws/rds/globalcluster/#example-usage
which seems to miss many of the comments in https://github.com/pulumi/terraform-provider-aws/blob/upstream-v3.7.0/website/docs/r/rds_global_cluster.html.markdown

**Comment by lukehoban** [comment]
This is very different in the [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/).  Will close this for now.
