### ISSUE TITLE
What is _var?

### ISSUE THREAD

**Issue by joehillen** [pulumi/tf2pulumi#214]
These examples use `_var` but the text refers to `&{...}`. 

https://github.com/pulumi/pulumi-aws/blob/6c13f319a64f3fdf2c71cb3808715a12c2322f0d/sdk/nodejs/iam/getPolicyDocument.ts#L32

Is `_var` supposed to work or is this example broken?

**Comment by pgavlin** [comment]
// These examples use _var but the text refers to &{...}.

The `&` does appear to be a bug--that character should be a `$` if I'm reading the [AWS docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html) correctly.

**Comment by joehillen** [comment]
`${...}` conflicts with Javascript's [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), so I think `&{...}` is supposed to be used instead, as noted [here](https://github.com/pulumi/pulumi-aws/blob/6c13f319a64f3fdf2c71cb3808715a12c2322f0d/sdk/nodejs/iam/getPolicyDocument.ts#L62-L68)

`_var` is not in scope, so it definitely should not be in the example

**Comment by pgavlin** [comment]
> ${...} conflicts with Javascript's template literals, so I think &{...} is supposed to be used instead, as noted here

Ah, excellent. Thanks for the pointer :)

> `_var` is not in scope, so it definitely should not be in the example

These examples are converted from snippets of HCL or HCL2 in the documentation for the corresponding Terraform provider. In this case, the source example refers to a configuration variable that it does not define. We believe that in these cases it is more useful to convert the example even though it has an error than it is to drop the example entirely. I think that in this particular set of circumstances--i.e. missing configuration variables--we could do better and automatically insert a definition, but in the general case there isn't much more we can do. I've files #216 to track the possibility of synthesizing configuration variables.
