### ISSUE TITLE
Helm support?

### ISSUE THREAD

**Issue by crubier** [pulumi/tf2pulumi#218]
I can't manage to make tf2pulumi to work with a terraform project involving helm. I get the following message

```
$ tf2pulumi --target-language typescript                         
error: no resource plugin 'helm' found in the workspace or on your $PATH
```

There is no "Helm" plugin, so the best I could do was this, but it did not solve the problem

```
$ pulumi plugin install resource kubernetes 2.6.2 
[resource plugin kubernetes-2.6.2] installing
Downloading plugin: 28.65 MiB / 28.65 MiB [=========================] 100.00% 4s
Moving plugin... done.
```

**Comment by viveklak** [comment]
Could you provide a bit more information on the original terraform you are trying to convert?

**Comment by crubier** [comment]
It uses the helm provider:

```
provider "helm" {
  version = "1.0.0"

  debug       = true 
  helm_driver = "secret" 

  kubernetes {
    config_path = "${path.cwd}/../outputs/kubeconfig_${local.cluster_name}"
  }
}
```

And then it deploys some helm charts:

```
resource "helm_release" "foobar" {
  name      = "foobar"
  namespace = "application"
  chart     = "../../charts/foobar"
  version   = "1.1.2"

  set {
    name  = "nameOverride"
    value = "foobar"
  }
}
```

**Comment by viveklak** [comment]
We don't support the terraform helm provider. However, you may want to consider the helm support in our kubernetes provider https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/. Note however, that you will have to migrate to it manually (tf2pulumi will not be able to do this for you). There are examples of using Helm in our examples repo (e.g.  https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm) that might be helpful. Please feel free to ask questions on community slack if you have any about helm integration with pulumi.
