### ISSUE TITLE
error with tf2pulumi

### ISSUE THREAD

**Issue by rajagopalanrg** [pulumi/tf2pulumi#221]
I tried using tf2pulumi tool and I was able to convert small terraform file into pulumi but failed when I had a complex one.  Please help us know the issue in this.
Error message
PS C:\Users\New\Documents\projects\terraform\new32943>  tf2pulumi --target-language go
panic: fatal: An assertion has failed
 
goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/assert.go:26  
github.com/pulumi/tf2pulumi/convert.parseFile(0xc0006c9598, 0x1945b00, 0xc0001a7780, 0xc000115428, 0x8, 0x0, 0x0)
        /home/runner/work/tf2pulumi/tf2pulumi/convert/tf12.go:34 +0x2ca
github.com/pulumi/tf2pulumi/convert.parseTF12(0x10000, 0x0, 0x0, 0x1945b00, 0xc0001a7780, 0x0, 0x0, 0x0, 0x19084e0, 0x239e6a0, ...)        
        /home/runner/work/tf2pulumi/tf2pulumi/convert/tf12.go:65 +0x256
github.com/pulumi/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x1945b00, 0xc0001a7780, 0x0, 0x0, 0x0, 0x19084e0, 0x239e6a0, ...)
        /home/runner/work/tf2pulumi/tf2pulumi/convert/convert.go:97 +0x11b
main.main.func1(0xc0001d9080, 0xc0001a76e0, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0xed
github.com/spf13/cobra.(*Command).execute(0xc0001d9080, 0xc000064050, 0x2, 0x3, 0xc0001d9080, 0xc000064050)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x45a
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d9080, 0xc00063ff50, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x58f

**Comment by aidapsibr** [comment]
Seeing the same issue down to the line numbers on v .10

**Comment by iarovyi** [comment]
Have this issue with terraform 13 and `tf2pulumi
0.11.1`

**Comment by aviflax** [comment]
Potential dup of #217.

I’m experiencing the same problem.

* M1 Mac running MacOS 11.6.1
* Terraform v1.0.11
* tf2pulumi v0.11.1

<details><summary>Output of <code>pulumi about</code></summary>

```shell
$ pulumi about
CLI          
Version      3.17.1
Go Version   go1.17.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.28.0
python  unknown

Host     
OS       darwin
Version  11.6.1
Arch     arm64

This project is written in python (/opt/homebrew/bin/python3 v3.9.8)

Backend  
Name     pulumi.com
URL      https://app.pulumi.com/aviflax
User     aviflax

NAME        VERSION
pip         21.3.1
pulumi-aws  4.28.0
setuptools  59.1.1
wheel       0.37.0
```

</details>

<details><summary>Output of <code>tf2pulumi</code></summary>

```shell
$ tf2pulumi --target-language python
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/fail.go:25
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.convertTF12(0x14000138b00, 0xa, 0x10, 0x10000, 0x0, 0x0, 0x101535ab8, 0x1400002e8c0, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/tf12.go:156 +0x17dc
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x101535ab8, 0x1400002e8c0, 0x0, 0x0, 0x0, 0x101504ba8, 0x101d73b20, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/convert.go:107 +0x264
main.main.func1(0x140000aa580, 0x1400002e880, 0x0, 0x2, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0xb8
github.com/spf13/cobra.(*Command).execute(0x140000aa580, 0x14000186190, 0x2, 0x2, 0x140000aa580, 0x14000186190)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x140000aa580, 0x140008bff40, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x258
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x4e8
```

</details>


----

#217 has been open since 2010-10-29 and this issue has been open since 2020-12-20. It’s hard to have confidence in a tool when its maintainers don’t seem particularly on top of bugs. Don’t get me wrong, the core Pulumi tool is fantastic and I’ve been very impressed by the responsiveness and communication of its maintainers. But this specific tool has already garnered a reputation, in my (small) org, of being unreliable and not worth the trouble of even trying it. So I suggest to Pulumi, the corporation, to either invest in making this tool robust and well-supported, or discontinue it and remove it from your marketing materials and docs.

**Comment by KTamas** [comment]
Same error. M1 Pro MBP, macOS 12.3.1, Terraform state is 0.15.1, tf2pulumi is the latest from homebrew but I also compiled my own from git and that didn't change anything.

Error:

```panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/Users/LocalAdmin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/Users/LocalAdmin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/fail.go:25
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.convertTF12({0x14000227400, 0x21, 0x100911070?}, {0x0, 0x0, 0x1, 0x0, 0x0, {0x0, 0x0}, ...})
	/Users/LocalAdmin/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/tf12.go:156 +0x14fc
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.Convert({0x0, 0x0, 0x1, 0x0, 0x0, {0x0, 0x0}, {0x101af0710, 0x1400007dbe0}, 0x0, ...})
	/Users/LocalAdmin/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/convert.go:107 +0x440
main.main.func1(0x140000d2b00?, {0x10155a81a?, 0x2?, 0x2?})
	/Users/LocalAdmin/src/tf2pulumi/main.go:52 +0xe8
github.com/spf13/cobra.(*Command).execute(0x140000d2b00, {0x1400003c1c0, 0x2, 0x2})
	/Users/LocalAdmin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x140000d2b00)
	/Users/LocalAdmin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/LocalAdmin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/LocalAdmin/src/tf2pulumi/main.go:117 +0x414
```

Gotta say, doesn't inspire a lot of confidence in Pulumi as a tool we're currently evaluating switching to.

**Comment by phene** [comment]
Ran into the exact same issue just now:

```
$ tf2pulumi --target-language python
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/fail.go:25
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.convertTF12(0xc0008175a0, 0x3, 0x4, 0x10000, 0x0, 0x0, 0x2517d78, 0xc0006d6c20, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/tf12.go:156 +0x1e8b
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x2517d78, 0xc0006d6c20, 0x0, 0x0, 0x0, 0x24e7860, 0x2d73ee0, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/convert.go:107 +0x3bc
main.main.func1(0xc000464dc0, 0xc0006d6be0, 0x0, 0x2, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0x105
github.com/spf13/cobra.(*Command).execute(0xc000464dc0, 0xc00010c190, 0x2, 0x2, 0xc000464dc0, 0xc00010c190)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000464dc0, 0xc0007fff50, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x593
```

**Comment by Brocaneli** [comment]
The same happened here

`tf2pulumi --target-language go
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.19.0/go/common/util/contract/fail.go:25
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.convertTF12(0xc00071e3c0, 0x2, 0x2, 0x10000, 0x0, 0x0, 0x2517d78, 0xc0004d7420, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/tf12.go:156 +0x1e8b
github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x2517d78, 0xc0004d7420, 0x0, 0x0, 0x0, 0x24e7860, 0x2d73ee0, ...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tf2pulumi/convert/convert.go:107 +0x3bc
main.main.func1(0xc00046eb00, 0xc0004d73e0, 0x0, 0x2, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0x105
github.com/spf13/cobra.(*Command).execute(0xc00046eb00, 0xc000118190, 0x2, 0x2, 0xc00046eb00, 0xc000118190)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00046eb00, 0xc0008c9f50, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x593`

**Comment by bradyburke** [comment]
Same error occurring as @Brocaneli

**Comment by joeduffy** [comment]
@Frassle Is this fixed with the new converter work?

**Comment by lukehoban** [comment]
This is fixed with the new [`pulumi convert --from terraform`](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) feature. That feature is built on a brand new Terraform paerser and converter, which supports effectively all of modern Terraform by default.  Check it out and let us know if there are any remaining issues for your codebases!
