### ISSUE TITLE
tf2pulumi | Error: no resource plugin 'template' found in the workspace or on your $PATH

### ISSUE THREAD

**Issue by deepakjd2004** [pulumi/tf2pulumi#228]
I am trying to convert existing terraform files to pulumi using tf2pulumi.

bash-3.2$ tf2pulumi --target-language python
error: no resource plugin 'template' found in the workspace or on your $PATH

Tried ignoring missing plugin but no luck

bash-3.2$ tf2pulumi --allow-missing-plugins --target-language python
error: no resource plugin 'template' found in the workspace or on your $PATH

**Comment by leezen** [comment]
Have tried running `pulumi plugin install resource terraform-template 0.16.0`?

**Comment by deepakjd2004** [comment]
Thanks it moved forward but now getting.

bash-3.2$ tf2pulumi --target-language python
error: rpc error: code = Unimplemented desc = unknown method GetSchema for service pulumirpc.ResourceProvider


I believe this is related to 
unknown method GetSchema for service pulumirpc.ResourceProvider #177
https://github.com/pulumi/tf2pulumi/issues/197
