### ISSUE TITLE
tfstate import.ts doesn't work with terraform 0.14.10 

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/tf2pulumi#231]
When following https://www.pulumi.com/docs/guides/adopting/from_terraform/#importing-resources 
the `pulumi up` throws an error:
```
    error: Running program '/Users/mitch/Downloads/tf-test' failed with an unhandled exception:
    Error: Only version '3' tfstate files currently supported: 4
```

## Expected behavior

The `pulumi  up` should import as expected.
(Note: the go-version of the import appears to support tfstate file version 4.)

## Current behavior

Throws the error as indicated above.

## Steps to reproduce

1. Confirm terraform version is 0.14.10 
2. Set up folder with attached main.tf file and do terraform apply.
[main.tf.txt](https://github.com/pulumi/tf2pulumi/files/6279850/main.tf.txt)
3. Execute the steps to tf2pulumi the main.tf and import the current TF state as described here: https://www.pulumi.com/docs/guides/adopting/from_terraform/#importing-resources 
4. See the error.

**Comment by lukehoban** [comment]
Potentially related: https://github.com/pulumi/tf2pulumi/issues/186

**Comment by Frassle** [comment]
tf2pulumi is deprecated, including the import code so this won't be fixed. But we are looking at writing a new state importer similar to the new converter.
