### ISSUE TITLE
"Error: undefined variable module" converting example Terraform repo for EKS

### ISSUE THREAD

**Issue by markfickett** [pulumi/tf2pulumi#244]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm attempting to convert https://github.com/hashicorp/learn-terraform-provision-eks-cluster to Pulumi (in Python).

### Steps to reproduce
1. Install Pulumi (shell install, v3.17.0)
2. Install tf2pulumi (linux binary x64, v0.11.1)
3. install aws and pulumi_random resources
4. execute `tf2pulumi --target-language python`:

Expected: convert without errors
Actual: lots of "undefined variable module" errors

```
Error: undefined variable module

  on security-groups.tf line 3:
  (source code not available)

Error: undefined variable module

  on security-groups.tf line 18:
  (source code not available)

Error: undefined variable module

  on eks-cluster.tf line 4:
  (source code not available)
... tens of more lines, mostly module variable errors
```

**Comment by leezen** [comment]
Unfortunately, there are currently some limitations in `tf2pulumi` with how it handles modules #239
