### ISSUE TITLE
error: no resource plugin 'null' found in the workspace or on your $PATH

### ISSUE THREAD

**Issue by johnpena** [pulumi/tf2pulumi#250]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm attempting to convert [github.com/christippett/terraform-google-cloud-sql-pgbouncer](https://github.com/christippett/terraform-google-cloud-sql-pgbouncer) to pulumi, targeting the go sdk. I've installed `tf2pulumi` using homebrew. When running tf2pulumi in the project, I get the following error:

```
error: no resource plugin 'null' found in the workspace or on your $PATH
```

### Steps to reproduce

```
git clone git@github.com:christippett/terraform-google-cloud-sql-pgbouncer.git
cd terraform-google-cloud-sql-pgbouncer
pulumi new go -f
tf2pulumi --target-language go
```

When running `pulumi new go -f`, I've used the defaults for everything.

**Comment by guineveresaenger** [comment]
Hi @johnpena - thank you for filing this issue!

I could reproduce this following your steps, and have added it to our backlog.

**Comment by RiaanVR** [comment]
Hi, @guineveresaenger any update on this ticket? My team has a fairly large set of Terraform projects which won't be feasible to manually re-write to pulumi.

**Comment by ponchofiesta** [comment]
On an internal project I get a similar message:
```
> tf2pulumi --target-language python --terraform-version 14
error: no resource plugin 'template' found in the workspace or on your $PATH
```
I did successfully run `terraform init` before resolving all plugins successfully.

**Comment by Frassle** [comment]
The new converter is tolerant to missing providers, but also null is now bridged.

**Comment by johnpena** [comment]
Thank you for the fix and the update!
