### ISSUE TITLE
Run analytics against the new converter

### ISSUE THREAD

**Issue by justinvp** [pulumi/tf2pulumi#265]
We need to get a sense for how the new WIP converter compares to the old converter, what the gaps are, and if the tfbridged examples are a useful dataset to help prioritize missing TF features and intrinsics.

The outcome of this analysis should be a prioritized list of gaps to address in the new converter.

**Comment by dixler** [comment]
I found out that you need to export PULUMI_EXPERIMENTAL=1 on fraser's branch to pull his changes.

here's the commit with the diff:
https://github.com/pulumi/home/commit/76da73968aeb865e7e2e281b6c168f14050b0196

note: github won't display the diff in the browser.

**Comment by justinvp** [comment]
We did the analysis against the tier 1 tfbridge provider examples, and while it was a good exercise to see how the new converter is doing (it's an improvement overall) the examples aren't using enough modern TF to be useful for prioritization. I'm going to close this issue as complete and open a new issue that tracks doing an analysis of a real world TF code base.
