### ISSUE TITLE
Handle bare variables better

### ISSUE THREAD

**Issue by joeduffy** [pulumi/tf2pulumi#49]
This HCL:

```hcl
request_parameters = {
  "method.request.header.X-Some-Header"         = true
  "method.request.querystring.some-query-param" = true
}
```

Results in this Pulumi TypeScript:

```typescript
import * as pulumi from "@pulumi/pulumi";
```

I'm not sure we can do better at this, because it's just a variable fragment, however the translation for this snippet is a bit odd. I wonder if we should just error out if the resulting program is "empty."

**Comment by pgavlin** [comment]
> I wonder if we should just error out if the resulting program is "empty."

How about simply not generating anything if the IL is empty?
